### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by Jia-Xiu** [willros/nanomux#2]
Hi William,

I've asked our dry lab manager to install your package on our HPC. However, we are encountering a problem. Please refer to the error message below. Do you have any suggestions to solve the issue?

Thanks in advance.

Best,
Xiu

`pip install -e .`
Obtaining file:///home/tools/nanomux/nanomux
  Preparing metadata (setup.py) ... done
Collecting pyfastx==2.0.2
  Using cached pyfastx-2.0.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Requirement already satisfied: polars in /home/groups/VEO/tools/nanomux/myenv/lib/python3.6/site-packages (from nanomux==0.1.0) (0.12.5)
ERROR: Could not find a version that satisfies the requirement polars-ds (from nanomux) (from versions: none)
ERROR: No matching distribution found for polars-ds

`pip install polars-ds==0.1.2`
ERROR: Could not find a version that satisfies the requirement polars-ds==0.1.2 (from versions: none)
ERROR: No matching distribution found for polars-ds==0.1.2

**Comment by willros** [comment]
Hi,

Hmm, the polars-ds version should be 0.4.4 (*i.e.* the latest), so pip install polars-ds should be enough. 

I don't know why it says 0.1.2.

Try again with that change. I cloned the repo again fresh and tried on our server and it worked. 

Thanks for letting me know,
William

**Comment by Jia-Xiu** [comment]
Hi, 
we found out that it was the version of python. It did not work with python3 (installing the correct version of polars-ds), but it worked with python3.9.
Best,
Xiu

**Comment by willros** [comment]
I see. Thanks for the update.

Let me know how the package works for you!
William
