### ISSUE TITLE
after trim two samples lost all the reads

### ISSUE THREAD

**Issue by Jia-Xiu** [willros/nanomux#5]
Hi @willros ,

I demultiplexed my reads again with the --trim option. Compared to --no-trim, I lost on average 8.7 reads per sample (Min.: 0, 1st Qu.: 3,  Median: 7, 3rd Qu.: 12, Max: 57). What I don't understand is that 2 samples are completely lost after trimming, which means they lost all of their 57, and 52 reads, respectively. These are my negative PCR controls. When I check the reads without trimming, they are assigned correctly. Do you have any idea what has happened? How can nanomux prevent this from happening?

Thanks,
Xiu

**Comment by willros** [comment]
Maybe they become shorter than the minimum length after trimming and are therefore filtered away?

**Comment by Jia-Xiu** [comment]
Sorry, I just checked my log file, it is because I set "minimum_reads: 100". May I ask when the filtering step happens? I thought the filtering step happened before searching. Is this correct?
Have a good day,
Xiu

**Comment by willros** [comment]
Actually, it is filtering before and after removal of barcodes.

**Comment by Jia-Xiu** [comment]
Thank you! Now it is clear to me. Do you think it is feasible to set two ranges of filter parameters? For example, a wider range to find the barcode, and a stricter one after removing the barcodes?
For example, I need a wider range to find the barcode before searching. In my case I used 1500-2600. Maybe it is better to make the filter in a narrower range after removing the barcodes, like 1450-1520? Just a thought, it's not very necessary as filtering the final fasta files would not be difficult.

**Comment by Jia-Xiu** [comment]
Another request, is it possible to make the fq files more concise? For example, one of my sample names is like this 'name'_8060_reads_nanomuxed.fq. I found it is very convenient to have the number of reads in the filename. However, we can also check the numbers in the csv file. To make it easier to process the files, I wonder if it is possible to give options to make it just like 'name'.fq? Thanks!

**Comment by Jia-Xiu** [comment]
Hi @willros,

I noticed that some samples are dropped out from the summary csv file if no reads are assigned to those samples. I was wondering if it is possible to include the zero read sample in the csv list. This will make it easier to compare the results. 

Thank you for your consideration.

Best,
Xiu

**Comment by willros** [comment]
I have now implemented your suggestions. Look at the new readme.

Thanks for the input!
William

**Comment by Jia-Xiu** [comment]
Thanks a lot for incorporating these changes! I noticed that there is only one option for "Maximum length of read", but not like "READ_LEN_MIN" that has options before searching for barcodes and after finding barcodes. I found it makes more sense to have a longer maximum length of reads before search barcodes, and remove long reads after finding barcodes. Is it feasible?
Best,
Xiu
