### ISSUE TITLE
Encoded output fq files

### ISSUE THREAD

**Issue by Jeepee8820** [willros/nanomux#8]
Hi @willros,

Thanks for this tool. The demultiplexing seems to work fine, but I have an issue: the output fq files are encoded on my side.
I am not sure which encoding it is. The same thing happens when the `--no-parquet` option is specified.
Thanks in advance for considering this issue.
Sincerely

**Comment by willros** [comment]
Hi @Jeepee8820 

The files are gzipped. Gunzip or look at them with zless or something else. 

You should check out my other project, nanomux_c. Is it much faster than this version and outputs the same results. Try it and tell me what you think!

**Comment by Jeepee8820** [comment]
Hi @willros,

Thanks for your prompt feedback. 
The gzip format was kind of what I was expecting but it did not fit with the file extension.
Nanomux was indeed a bit slow, so I will be happy check out your new project.
Sincerely
